### ISSUE TITLE
AWS NLB Usage Warning still needed ?

### ISSUE THREAD

**Issue by yogeek** [istio/istio.io#5239]
In the doc [Configuring Istio Ingress with AWS NLB](https://istio.io/blog/2018/aws-nlb/#prerequisites), a warning mention a bug in K8S that prevented to create multiple clusters in the same AZ when using NLB ingress. 

However, the referenced issue kubernetes/kubernetes#69264 seems to be fixed by kubernetes/kubernetes#74910.

I wondered if this warning is still needed because, although it seems to be fixed, I may have the same problem as stated in [this dicuss topic](https://discuss.istio.io/t/aws-nlb-ingress-gateways-error-with-multiple-clusters/4185) 

Does anyone here could tell me if the issue is really fixed ? If so, I would make a PR to remove the warning from the corresponding doc.

**Comment by TarekAS** [comment]
The bug is only fixed in 1.15 right? Therefore, we might still need this warning.

**Comment by davi7461** [comment]
Can we have an update on this?

**Comment by pwjagrullar** [comment]
The doc also states that "Usage of AWS nlb on Kubernetes is an Alpha feature and not recommended for production clusters.".

Is this still valid now 2 years later or is it ok to use AWS NLB in production clusters?

**Comment by sbogdanovic** [comment]
Besides problems with TLS in versions pre 1.15 and the still existing problem with multiple clusters in the same zone, are there any other known issues with NLB?

**Comment by kanapuli** [comment]
Istio NLB seems to modify Security groups to expose the nodeports to all IPs. This could be a security problem.

**Comment by howardjohn** [comment]
The blogs are considered a snapshot in time and have a warning "This blog post was written assuming Istio 1.0, so some of this content may now be outdated.". 

We do not intend to keep every blog 100% up to date
